name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java (adjust the version if needed)
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: 23
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # Step 3: Build the project using Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Step 4: Create a release artifact
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: build/libs/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download the artifact from the build job
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-output

      # Step 2: Publish a release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: "Release v${{ github.run_number }}"
          body: |
            Automated release for commit: ${{ github.sha }}
          draft: false
          prerelease: true  # Mark as a prerelease/beta if needed
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          result-encoding: string
          script: |
            const fs = require("fs")
            return fs.readdirSync("build/libs/").filter(e => !e.endsWith("dev.jar") && !e.endsWith("sources.jar") && e.endsWith(".jar"))[0].replace(".jar", "");

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.fname.outputs.result }}
          path: build/libs/

