name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java (adjust the version if needed)
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: 23
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # Step 3: Build the project using Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Step 4: Set the JAR file name dynamically
      - name: Get JAR file name
        id: jar_file
        run: |
          JAR_NAME=$(ls build/libs/*.jar | head -n 1 | xargs -n 1 basename)
          echo "JAR_FILE=$JAR_NAME" >> $GITHUB_ENV

      # Step 5: Upload the JAR file
      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: my-mod-jar
          path: build/libs/${{ env.JAR_FILE }}
